import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type CatalogEntry = {
  variant: string;
  id: string;
  displayName: string;
  shortName: string;
  hotkey: string;
  submitDefault: boolean;
  logo: string;
  color: string;
  textColor?: string;
};

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const catalogPath = resolve(repoRoot, "crates/tokscale-core/client-catalog.json");
const outputPath = resolve(
  repoRoot,
  "packages/frontend/src/lib/clientRegistry.generated.ts"
);
const checkOnly = process.argv.includes("--check");

function assertString(value: unknown, field: string, index: number): asserts value is string {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`client-catalog[${index}].${field} must be a non-empty string`);
  }
}

function assertBoolean(value: unknown, field: string, index: number): asserts value is boolean {
  if (typeof value !== "boolean") {
    throw new Error(`client-catalog[${index}].${field} must be a boolean`);
  }
}

function readCatalog(): CatalogEntry[] {
  const raw = JSON.parse(readFileSync(catalogPath, "utf8")) as unknown;
  if (!Array.isArray(raw) || raw.length === 0) {
    throw new Error("client-catalog.json must be a non-empty array");
  }

  const ids = new Set<string>();
  return raw.map((entry, index) => {
    if (!entry || typeof entry !== "object") {
      throw new Error(`client-catalog[${index}] must be an object`);
    }

    const record = entry as Record<string, unknown>;
    assertString(record.variant, "variant", index);
    assertString(record.id, "id", index);
    assertString(record.displayName, "displayName", index);
    assertString(record.shortName, "shortName", index);
    assertString(record.hotkey, "hotkey", index);
    assertBoolean(record.submitDefault, "submitDefault", index);
    assertString(record.logo, "logo", index);
    assertString(record.color, "color", index);

    if (!/^[a-z0-9][a-z0-9-]*$/.test(record.id)) {
      throw new Error(`client-catalog[${index}].id is not canonical lowercase: ${record.id}`);
    }
    if (ids.has(record.id)) {
      throw new Error(`duplicate client id in catalog: ${record.id}`);
    }
    ids.add(record.id);

    if ([...record.hotkey].length !== 1) {
      throw new Error(`client-catalog[${index}].hotkey must be one character`);
    }
    if (record.textColor !== undefined) {
      assertString(record.textColor, "textColor", index);
    }

    return {
      variant: record.variant,
      id: record.id,
      displayName: record.displayName,
      shortName: record.shortName,
      hotkey: record.hotkey,
      submitDefault: record.submitDefault,
      logo: record.logo,
      color: record.color,
      textColor: record.textColor,
    };
  });
}

function literal(value: string | boolean | undefined): string {
  if (value === undefined) return "undefined";
  return JSON.stringify(value);
}

function generate(catalog: CatalogEntry[]): string {
  const ids = catalog.map((entry) => `  ${JSON.stringify(entry.id)},`).join("\n");
  const registry = catalog
    .map((entry) => {
      return [
        `  ${JSON.stringify(entry.id)}: {`,
        `    displayName: ${literal(entry.displayName)},`,
        `    shortName: ${literal(entry.shortName)},`,
        `    logo: ${literal(entry.logo)},`,
        `    color: ${literal(entry.color)},`,
        `    textColor: ${literal(entry.textColor)},`,
        `    submitDefault: ${literal(entry.submitDefault)},`,
        "  },",
      ].join("\n");
    })
    .join("\n");

  return `// @generated by scripts/generate-client-registry.ts
// Do not edit by hand.

export const BASE_CLIENT_TYPES = [
${ids}
] as const;

export type BaseClientType = typeof BASE_CLIENT_TYPES[number];
export type CcMirrorClientType = \`cc-mirror/\${string}\`;
export type ClientType = BaseClientType | CcMirrorClientType;

export const CLIENT_REGISTRY = {
${registry}
} as const satisfies Record<
  BaseClientType,
  {
    displayName: string;
    shortName: string;
    logo: string;
    color: string;
    textColor: string | undefined;
    submitDefault: boolean;
  }
>;
`;
}

const generated = generate(readCatalog());

if (checkOnly) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== generated) {
    throw new Error(`${outputPath} is out of date; run bun scripts/generate-client-registry.ts`);
  }
} else {
  writeFileSync(outputPath, generated);
}
