#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT_UNDER_TEST="${ROOT_DIR}/scripts/check-release-commit.sh"
COHERENCE_SCRIPT="${ROOT_DIR}/scripts/check-version-coherence.sh"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

git_config() {
  git config user.name "Test Runner"
  git config user.email "test@example.com"
}

write_manifests() {
  local version="$1"
  mkdir -p \
    packages/tokenx \
    packages/tokenx-darwin-arm64 \
    packages/tokenx-linux-x64-gnu \
    packages/tokenx-win32-x64-msvc

  cat > Cargo.toml <<EOF_MANIFEST
[workspace.package]
version = "${version}"
EOF_MANIFEST

  cat > Cargo.lock <<EOF_LOCK
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "tokenx"
version = "${version}"
dependencies = [
 "tokenx-engine",
]

[[package]]
name = "tokenx-engine"
version = "${version}"
EOF_LOCK

  cat > packages/tokenx/package.json <<EOF_MANIFEST
{
  "name": "@juya-ai/tokenx",
  "version": "${version}",
  "optionalDependencies": {
    "@juya-ai/tokenx-darwin-arm64": "${version}",
    "@juya-ai/tokenx-linux-x64-gnu": "${version}",
    "@juya-ai/tokenx-win32-x64-msvc": "${version}"
  }
}
EOF_MANIFEST

  for package_dir in \
    tokenx-darwin-arm64 \
    tokenx-linux-x64-gnu \
    tokenx-win32-x64-msvc; do
    cat > "packages/${package_dir}/package.json" <<EOF_MANIFEST
{
  "name": "@juya-ai/${package_dir}",
  "version": "${version}"
}
EOF_MANIFEST
  done
}

git_add_release_manifests() {
  git add -- \
    Cargo.toml \
    Cargo.lock \
    packages/tokenx/package.json \
    packages/tokenx-darwin-arm64/package.json \
    packages/tokenx-linux-x64-gnu/package.json \
    packages/tokenx-win32-x64-msvc/package.json
}

create_origin() {
  local prefix="$1"
  local origin="${TMP_DIR}/${prefix}-origin.git"
  local seed="${TMP_DIR}/${prefix}-seed"

  git init -q --bare "${origin}"
  git init -q "${seed}"
  (
    cd "${seed}"
    git_config
    git switch -qc main
    mkdir -p scripts
    cp "${SCRIPT_UNDER_TEST}" scripts/check-release-commit.sh
    cp "${COHERENCE_SCRIPT}" scripts/check-version-coherence.sh
    write_manifests 1.2.3
    git add .
    git commit -qm "seed release files"
    git remote add origin "${origin}"
    git push -q origin main
  )
  git --git-dir="${origin}" symbolic-ref HEAD refs/heads/main
  printf '%s\n' "${origin}"
}

clone_main() {
  local origin="$1"
  local work="$2"
  git clone -q "${origin}" "${work}"
  git -C "${work}" switch -q main
  git -C "${work}" config user.name "Test Runner"
  git -C "${work}" config user.email "test@example.com"
}

commit_release() {
  local work="$1"
  local version="$2"
  (
    cd "${work}"
    write_manifests "${version}"
    git_add_release_manifests
    git commit -qm "chore(release): bump version to ${version}"
    git push -q origin main
  )
}

run_check() {
  local work="$1"
  local event="$2"
  local release_sha="$3"
  local before_sha="$4"
  local version="$5"
  local output_file="$6"
  (
    cd "${work}"
    RELEASE_EVENT_NAME="${event}" \
      RELEASE_VERSION="${version}" \
      RELEASE_BEFORE_SHA="${before_sha}" \
      RELEASE_REF_NAME=main \
      RELEASE_REF_TYPE=branch \
      DEFAULT_BRANCH=main \
      EXPECTED_RELEASE_SHA="${release_sha}" \
      GITHUB_OUTPUT="${output_file}" \
      bash scripts/check-release-commit.sh
  )
}

test_accepts_release_only_version_push() {
  local origin work base_sha release_sha output_file
  origin="$(create_origin valid)"
  work="${TMP_DIR}/valid-work"
  clone_main "${origin}" "${work}"
  base_sha="$(git -C "${work}" rev-parse HEAD)"
  commit_release "${work}" 1.2.4
  release_sha="$(git -C "${work}" rev-parse HEAD)"
  output_file="${TMP_DIR}/valid-github-output.txt"

  run_check "${work}" push "${release_sha}" "${base_sha}" "" "${output_file}" >"${TMP_DIR}/valid-output.txt"

  grep -q '^should_publish=true$' "${output_file}"
  grep -q '^version=1.2.4$' "${output_file}"
  grep -q '^base_version=1.2.3$' "${output_file}"
  grep -q "^release_commit=${release_sha}$" "${output_file}"
  grep -q '^recovery=false$' "${output_file}"
}

test_skips_push_without_version_change() {
  local origin work base_sha head_sha output_file
  origin="$(create_origin no-version)"
  work="${TMP_DIR}/no-version-work"
  clone_main "${origin}" "${work}"
  base_sha="$(git -C "${work}" rev-parse HEAD)"
  (
    cd "${work}"
    echo "change" > README.md
    git add README.md
    git commit -qm "docs: update readme"
    git push -q origin main
  )
  head_sha="$(git -C "${work}" rev-parse HEAD)"
  output_file="${TMP_DIR}/no-version-github-output.txt"

  run_check "${work}" pull_request "${head_sha}" "${base_sha}" "" "${TMP_DIR}/no-version-pr-output.txt" >"${TMP_DIR}/no-version-pr-log.txt"
  grep -q "Release pull request OK: 1.2.3 -> 1.2.3" "${TMP_DIR}/no-version-pr-log.txt"

  run_check "${work}" push "${head_sha}" "${base_sha}" "" "${output_file}" >"${TMP_DIR}/no-version-output.txt"

  grep -q '^should_publish=false$' "${output_file}"
  grep -q "publishing is skipped" "${TMP_DIR}/no-version-output.txt"
}

test_rejects_version_push_with_non_release_files() {
  local origin work base_sha release_sha output_file
  origin="$(create_origin mixed)"
  work="${TMP_DIR}/mixed-work"
  clone_main "${origin}" "${work}"
  base_sha="$(git -C "${work}" rev-parse HEAD)"
  (
    cd "${work}"
    write_manifests 1.2.4
    echo "bundled code" > README.md
    git_add_release_manifests
    git add README.md
    git commit -qm "chore(release): mix release and code"
    git push -q origin main
  )
  release_sha="$(git -C "${work}" rev-parse HEAD)"
  output_file="${TMP_DIR}/mixed-github-output.txt"

  if run_check "${work}" pull_request "${release_sha}" "${base_sha}" "" "${TMP_DIR}/mixed-pr-output.txt" >"${TMP_DIR}/mixed-pr-log.txt" 2>&1; then
    echo "Expected a mixed release pull request to fail" >&2
    return 1
  fi
  grep -q "version-bump commits may only change release manifests" "${TMP_DIR}/mixed-pr-log.txt"

  if run_check "${work}" push "${release_sha}" "${base_sha}" "" "${output_file}" >"${TMP_DIR}/mixed-output.txt" 2>&1; then
    echo "Expected a mixed release commit to fail" >&2
    return 1
  fi

  grep -q "version-bump commits may only change release manifests" "${TMP_DIR}/mixed-output.txt"
}

test_auto_publish_rejects_stale_release_commit() {
  local origin work base_sha release_sha output_file
  origin="$(create_origin stale)"
  work="${TMP_DIR}/stale-work"
  clone_main "${origin}" "${work}"
  base_sha="$(git -C "${work}" rev-parse HEAD)"
  commit_release "${work}" 1.2.4
  release_sha="$(git -C "${work}" rev-parse HEAD)"
  (
    cd "${work}"
    echo "later" > README.md
    git add README.md
    git commit -qm "docs: advance main"
    git push -q origin main
    git checkout -q "${release_sha}"
  )
  output_file="${TMP_DIR}/stale-github-output.txt"

  if run_check "${work}" push "${release_sha}" "${base_sha}" "" "${output_file}" >"${TMP_DIR}/stale-output.txt" 2>&1; then
    echo "Expected a stale automatic release to fail" >&2
    return 1
  fi

  grep -q "Release commit is stale" "${TMP_DIR}/stale-output.txt"
}

test_recovery_accepts_exact_ancestor_release_commit() {
  local origin work release_sha output_file
  origin="$(create_origin recovery)"
  work="${TMP_DIR}/recovery-work"
  clone_main "${origin}" "${work}"
  commit_release "${work}" 1.2.4
  release_sha="$(git -C "${work}" rev-parse HEAD)"
  (
    cd "${work}"
    echo "later" > README.md
    git add README.md
    git commit -qm "docs: advance main"
    git push -q origin main
    git checkout -q "${release_sha}"
  )
  output_file="${TMP_DIR}/recovery-github-output.txt"

  run_check "${work}" workflow_dispatch "${release_sha}" "" 1.2.4 "${output_file}" >"${TMP_DIR}/recovery-output.txt"

  grep -q '^should_publish=true$' "${output_file}"
  grep -q '^recovery=true$' "${output_file}"
  grep -q "recovery=true" "${TMP_DIR}/recovery-output.txt"
}

test_recovery_rejects_later_commit_with_same_version() {
  local origin work later_sha output_file
  origin="$(create_origin wrong-recovery)"
  work="${TMP_DIR}/wrong-recovery-work"
  clone_main "${origin}" "${work}"
  commit_release "${work}" 1.2.4
  (
    cd "${work}"
    echo "later" > README.md
    git add README.md
    git commit -qm "docs: advance main"
    git push -q origin main
  )
  later_sha="$(git -C "${work}" rev-parse HEAD)"
  output_file="${TMP_DIR}/wrong-recovery-github-output.txt"

  if run_check "${work}" workflow_dispatch "${later_sha}" "" 1.2.4 "${output_file}" >"${TMP_DIR}/wrong-recovery-output.txt" 2>&1; then
    echo "Expected recovery from a non-release commit to fail" >&2
    return 1
  fi

  grep -q "did not introduce version 1.2.4" "${TMP_DIR}/wrong-recovery-output.txt"
}

test_accepts_release_only_version_push
test_skips_push_without_version_change
test_rejects_version_push_with_non_release_files
test_auto_publish_rejects_stale_release_commit
test_recovery_accepts_exact_ancestor_release_commit
test_recovery_rejects_later_commit_with_same_version

echo "check-release-commit tests passed"
