#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT_UNDER_TEST="${ROOT_DIR}/scripts/bump-release-version.sh"
COHERENCE_SCRIPT="${ROOT_DIR}/scripts/check-version-coherence.sh"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

write_manifests() {
  local version="$1"
  mkdir -p \
    packages/tokenx \
    packages/tokenx-darwin-arm64 \
    packages/tokenx-linux-x64-gnu \
    packages/tokenx-win32-x64-msvc

  cat > Cargo.toml <<EOF_MANIFEST
[workspace.package]
version = "${version}"
EOF_MANIFEST

  cat > Cargo.lock <<EOF_LOCK
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "tokenx"
version = "${version}"
dependencies = [
 "tokenx-engine",
]

[[package]]
name = "tokenx-engine"
version = "${version}"
EOF_LOCK

  cat > packages/tokenx/package.json <<EOF_MANIFEST
{
  "name": "@juya-ai/tokenx",
  "version": "${version}",
  "optionalDependencies": {
    "@juya-ai/tokenx-darwin-arm64": "${version}",
    "@juya-ai/tokenx-linux-x64-gnu": "${version}",
    "@juya-ai/tokenx-win32-x64-msvc": "${version}"
  }
}
EOF_MANIFEST

  for package_dir in \
    tokenx-darwin-arm64 \
    tokenx-linux-x64-gnu \
    tokenx-win32-x64-msvc; do
    cat > "packages/${package_dir}/package.json" <<EOF_MANIFEST
{
  "name": "@juya-ai/${package_dir}",
  "version": "${version}"
}
EOF_MANIFEST
  done
}

write_fake_cargo() {
  mkdir -p fake-bin
  cat > fake-bin/cargo <<'EOF_CARGO'
#!/usr/bin/env bash
set -euo pipefail
[[ "$*" == "update --workspace" ]]
version="$(python3 - <<'PY'
import pathlib
import re

text = pathlib.Path("Cargo.toml").read_text()
match = re.search(r'^version = "([^"]+)"', text, re.MULTILINE)
if not match:
    raise SystemExit("workspace version missing")
print(match.group(1))
PY
)"
python3 - "${version}" <<'PY'
import pathlib
import re
import sys

version = sys.argv[1]
path = pathlib.Path("Cargo.lock")
text = path.read_text()
for package in ("tokenx", "tokenx-engine"):
    text, count = re.subn(
        rf'(\[\[package\]\]\nname = "{package}"\nversion = ")([^"]+)(")',
        rf"\g<1>{version}\g<3>",
        text,
        count=1,
    )
    if count != 1:
        raise SystemExit(f"lock package missing: {package}")
path.write_text(text)
PY
EOF_CARGO
  chmod +x fake-bin/cargo
}

create_fixture() {
  local work="$1"
  local version="$2"
  mkdir -p "${work}/scripts"
  cp "${SCRIPT_UNDER_TEST}" "${work}/scripts/bump-release-version.sh"
  cp "${COHERENCE_SCRIPT}" "${work}/scripts/check-version-coherence.sh"
  (
    cd "${work}"
    write_manifests "${version}"
    write_fake_cargo
    git init -q
    git config user.name "Test Runner"
    git config user.email "test@example.com"
    git add .
    git commit -qm "seed"
  )
}

run_bump() {
  local work="$1"
  local request="$2"
  (
    cd "${work}"
    PATH="${work}/fake-bin:${PATH}" bash scripts/bump-release-version.sh "${request}"
  )
}

test_patch_bump_updates_every_release_manifest() {
  local work="${TMP_DIR}/patch"
  create_fixture "${work}" "4.3.0"

  run_bump "${work}" patch >"${TMP_DIR}/patch-output.txt"

  (
    cd "${work}"
    bash scripts/check-version-coherence.sh --expect-version 4.3.1
    test "$(git diff --name-only | wc -l)" -eq 6
  )
  grep -q "Prepared release version 4.3.0 -> 4.3.1" "${TMP_DIR}/patch-output.txt"
}

test_explicit_prerelease_uses_semver_precedence() {
  local work="${TMP_DIR}/prerelease"
  create_fixture "${work}" "4.4.0-beta.2"

  run_bump "${work}" 4.4.0-beta.10 >"${TMP_DIR}/prerelease-output.txt"

  (
    cd "${work}"
    bash scripts/check-version-coherence.sh --expect-version 4.4.0-beta.10
  )
}

test_rejects_non_increasing_version_without_changes() {
  local work="${TMP_DIR}/downgrade"
  create_fixture "${work}" "4.3.0"

  if run_bump "${work}" 4.2.0 >"${TMP_DIR}/downgrade-output.txt" 2>&1; then
    echo "Expected a version downgrade to fail" >&2
    return 1
  fi

  grep -q "must be greater than current version" "${TMP_DIR}/downgrade-output.txt"
  test -z "$(git -C "${work}" status --short)"
}

test_rejects_dirty_release_manifests() {
  local work="${TMP_DIR}/dirty"
  create_fixture "${work}" "4.3.0"
  printf '\n' >> "${work}/Cargo.toml"

  if run_bump "${work}" patch >"${TMP_DIR}/dirty-output.txt" 2>&1; then
    echo "Expected dirty release manifests to fail" >&2
    return 1
  fi

  grep -q "Release manifests contain unstaged changes" "${TMP_DIR}/dirty-output.txt"
}

test_patch_bump_updates_every_release_manifest
test_explicit_prerelease_uses_semver_precedence
test_rejects_non_increasing_version_without_changes
test_rejects_dirty_release_manifests

echo "bump-release-version tests passed"
