#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT_UNDER_TEST="${ROOT_DIR}/scripts/check-version-coherence.sh"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

write_release_manifests() {
  local version="$1"
  local lock_version="${2:-${version}}"

  mkdir -p \
    packages/tokenx \
    packages/tokenx-darwin-arm64 \
    packages/tokenx-linux-x64-gnu \
    packages/tokenx-win32-x64-msvc

  cat > Cargo.toml <<EOF_MANIFEST
[workspace]
members = [
  "crates/tokenx-engine",
  "crates/tokenx",
]

[workspace.package]
version = "${version}"
EOF_MANIFEST

  cat > Cargo.lock <<EOF_LOCK
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "tokenx"
version = "${lock_version}"
dependencies = [
 "tokenx-engine",
]

[[package]]
name = "tokenx-engine"
version = "${lock_version}"
EOF_LOCK

  cat > packages/tokenx/package.json <<EOF_MANIFEST
{
  "name": "@juya-ai/tokenx",
  "version": "${version}",
  "optionalDependencies": {
    "@juya-ai/tokenx-darwin-arm64": "${version}",
    "@juya-ai/tokenx-linux-x64-gnu": "${version}",
    "@juya-ai/tokenx-win32-x64-msvc": "${version}"
  }
}
EOF_MANIFEST

  for pkg in \
    tokenx-darwin-arm64 \
    tokenx-linux-x64-gnu \
    tokenx-win32-x64-msvc; do
    cat > "packages/${pkg}/package.json" <<EOF_MANIFEST
{
  "name": "@juya-ai/${pkg}",
  "version": "${version}"
}
EOF_MANIFEST
  done
}

test_rejects_stale_workspace_versions_in_cargo_lock() {
  local work="${TMP_DIR}/stale-lock"
  mkdir -p "${work}/scripts"
  cp "${SCRIPT_UNDER_TEST}" "${work}/scripts/check-version-coherence.sh"
  (
    cd "${work}"
    write_release_manifests "3.0.0" "2.1.3"

    local output="${TMP_DIR}/stale-lock-output.txt"
    if bash scripts/check-version-coherence.sh --expect-version "3.0.0" >"${output}" 2>&1; then
      echo "Expected stale Cargo.lock package versions to fail" >&2
      return 1
    fi

    grep -q "Cargo.lock package tokenx: expected 3.0.0, found 2.1.3" "${output}"
    grep -q "Cargo.lock package tokenx-engine: expected 3.0.0, found 2.1.3" "${output}"
  )
}

test_accepts_matching_workspace_versions_in_cargo_lock() {
  local work="${TMP_DIR}/matching-lock"
  mkdir -p "${work}/scripts"
  cp "${SCRIPT_UNDER_TEST}" "${work}/scripts/check-version-coherence.sh"
  (
    cd "${work}"
    write_release_manifests "3.0.0"
    bash scripts/check-version-coherence.sh --expect-version "3.0.0" >"${TMP_DIR}/matching-lock-output.txt" 2>&1
  )
}

test_ignores_registry_duplicate_names_in_cargo_lock() {
  local work="${TMP_DIR}/registry-duplicate-lock"
  mkdir -p "${work}/scripts"
  cp "${SCRIPT_UNDER_TEST}" "${work}/scripts/check-version-coherence.sh"
  (
    cd "${work}"
    write_release_manifests "3.0.0"
    cat >> Cargo.lock <<'EOF_LOCK'

[[package]]
name = "tokenx-engine"
version = "2.1.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
EOF_LOCK

    bash scripts/check-version-coherence.sh --expect-version "3.0.0" >"${TMP_DIR}/registry-duplicate-lock-output.txt" 2>&1
  )
}

test_rejects_unsupported_platform_package_when_manifest_and_optional_dependency_match() {
  local work="${TMP_DIR}/unsupported-platform-package"
  mkdir -p "${work}/scripts"
  cp "${SCRIPT_UNDER_TEST}" "${work}/scripts/check-version-coherence.sh"
  (
    cd "${work}"
    write_release_manifests "3.0.0"
    mkdir -p packages/tokenx-linux-riscv64-gnu
    cat > packages/tokenx-linux-riscv64-gnu/package.json <<'EOF_MANIFEST'
{
  "name": "@juya-ai/tokenx-linux-riscv64-gnu",
  "version": "3.0.0"
}
EOF_MANIFEST
    python3 - <<'PY'
import json
import pathlib

path = pathlib.Path("packages/tokenx/package.json")
manifest = json.loads(path.read_text())
manifest["optionalDependencies"]["@juya-ai/tokenx-linux-riscv64-gnu"] = "3.0.0"
path.write_text(json.dumps(manifest, indent=2) + "\n")
PY

    local output="${TMP_DIR}/unsupported-platform-package-output.txt"
    if bash scripts/check-version-coherence.sh --expect-version "3.0.0" >"${output}" 2>&1; then
      echo "Expected unsupported platform package to fail" >&2
      return 1
    fi

    grep -q "Unsupported platform package manifests: \\['@juya-ai/tokenx-linux-riscv64-gnu'\\]" "${output}"
    grep -q "Unsupported platform optionalDependencies: \\['@juya-ai/tokenx-linux-riscv64-gnu'\\]" "${output}"
  )
}

test_rejects_missing_canonical_platform_when_manifest_and_optional_dependency_are_removed() {
  local work="${TMP_DIR}/missing-canonical-platform"
  mkdir -p "${work}/scripts"
  cp "${SCRIPT_UNDER_TEST}" "${work}/scripts/check-version-coherence.sh"
  (
    cd "${work}"
    write_release_manifests "3.0.0"
    rm -rf packages/tokenx-win32-x64-msvc
    python3 - <<'PY'
import json
import pathlib

path = pathlib.Path("packages/tokenx/package.json")
manifest = json.loads(path.read_text())
manifest["optionalDependencies"].pop("@juya-ai/tokenx-win32-x64-msvc")
path.write_text(json.dumps(manifest, indent=2) + "\n")
PY

    local output="${TMP_DIR}/missing-canonical-platform-output.txt"
    if bash scripts/check-version-coherence.sh --expect-version "3.0.0" >"${output}" 2>&1; then
      echo "Expected missing canonical platform to fail" >&2
      return 1
    fi

    grep -q "Missing required platform package manifests: \\['@juya-ai/tokenx-win32-x64-msvc'\\]" "${output}"
    grep -q "Missing required platform optionalDependencies: \\['@juya-ai/tokenx-win32-x64-msvc'\\]" "${output}"
  )
}

test_rejects_stale_workspace_versions_in_cargo_lock
test_accepts_matching_workspace_versions_in_cargo_lock
test_ignores_registry_duplicate_names_in_cargo_lock
test_rejects_unsupported_platform_package_when_manifest_and_optional_dependency_match
test_rejects_missing_canonical_platform_when_manifest_and_optional_dependency_are_removed

echo "check-version-coherence tests passed"
